### GENERAL SETTINGS ###

# Site settings
title: Bikaner Ropes
description: "Binaner Ropes company's website"
analytics: UA-25759569-4 #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: ""

# gems setting to generate sitemap
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#356ea1" #"#F70031"
  primary_rgb: "0,115,200" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  faqs:
    output: true

### CONTACT SETTINGS ###

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Binaner Ropes companity's website"
theme: jekyll-theme-cayman
